// Auto-generated by scripts/generate-aws-icons.js
export const generatedAwsIcons = {
  name: 'aws',
  title: 'AWS Official Icons (ES)',
  icons: [
  {
    "id": "Athena",
    "name": "Athena",
    "title": "Athena",
    "category": "Analítica",
    "collection": "Analítica",
    "url": "/pngs/Analytics/Athena.png?v=1771024599484",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Clean-Rooms",
    "name": "Clean Rooms",
    "title": "Clean Rooms",
    "category": "Analítica",
    "collection": "Analítica",
    "url": "/pngs/Analytics/Clean-Rooms.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "CloudSearch",
    "name": "CloudSearch",
    "title": "CloudSearch",
    "category": "Analítica",
    "collection": "Analítica",
    "url": "/pngs/Analytics/CloudSearch.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Data-Exchange",
    "name": "Data Exchange",
    "title": "Data Exchange",
    "category": "Analítica",
    "collection": "Analítica",
    "url": "/pngs/Analytics/Data-Exchange.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Data-Pipeline",
    "name": "Data Pipeline",
    "title": "Data Pipeline",
    "category": "Analítica",
    "collection": "Analítica",
    "url": "/pngs/Analytics/Data-Pipeline.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "DataZone",
    "name": "DataZone",
    "title": "DataZone",
    "category": "Analítica",
    "collection": "Analítica",
    "url": "/pngs/Analytics/DataZone.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "EMR",
    "name": "EMR",
    "title": "EMR",
    "category": "Analítica",
    "collection": "Analítica",
    "url": "/pngs/Analytics/EMR.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "FinSpace",
    "name": "FinSpace",
    "title": "FinSpace",
    "category": "Analítica",
    "collection": "Analítica",
    "url": "/pngs/Analytics/FinSpace.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Glue-DataBrew",
    "name": "Glue DataBrew",
    "title": "Glue DataBrew",
    "category": "Analítica",
    "collection": "Analítica",
    "url": "/pngs/Analytics/Glue-DataBrew.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Glue-Elastic-Views",
    "name": "Glue Elastic Views",
    "title": "Glue Elastic Views",
    "category": "Analítica",
    "collection": "Analítica",
    "url": "/pngs/Analytics/Glue-Elastic-Views.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Glue",
    "name": "Glue",
    "title": "Glue",
    "category": "Analítica",
    "collection": "Analítica",
    "url": "/pngs/Analytics/Glue.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Kinesis-Data-Analytics",
    "name": "Kinesis Data Analytics",
    "title": "Kinesis Data Analytics",
    "category": "Analítica",
    "collection": "Analítica",
    "url": "/pngs/Analytics/Kinesis-Data-Analytics.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Kinesis-Data-Streams",
    "name": "Kinesis Data Streams",
    "title": "Kinesis Data Streams",
    "category": "Analítica",
    "collection": "Analítica",
    "url": "/pngs/Analytics/Kinesis-Data-Streams.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Kinesis-Firehose",
    "name": "Kinesis Firehose",
    "title": "Kinesis Firehose",
    "category": "Analítica",
    "collection": "Analítica",
    "url": "/pngs/Analytics/Kinesis-Firehose.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Kinesis-Video-Streams",
    "name": "Kinesis Video Streams",
    "title": "Kinesis Video Streams",
    "category": "Analítica",
    "collection": "Analítica",
    "url": "/pngs/Analytics/Kinesis-Video-Streams.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Kinesis",
    "name": "Kinesis",
    "title": "Kinesis",
    "category": "Analítica",
    "collection": "Analítica",
    "url": "/pngs/Analytics/Kinesis.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Lake-Formation",
    "name": "Lake Formation",
    "title": "Lake Formation",
    "category": "Analítica",
    "collection": "Analítica",
    "url": "/pngs/Analytics/Lake-Formation.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Managed-Streaming-for-Apache-Kafka",
    "name": "Managed Streaming for Apache Kafka",
    "title": "Managed Streaming for Apache Kafka",
    "category": "Analítica",
    "collection": "Analítica",
    "url": "/pngs/Analytics/Managed-Streaming-for-Apache-Kafka.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "OpenSearch-Service",
    "name": "OpenSearch Service",
    "title": "OpenSearch Service",
    "category": "Analítica",
    "collection": "Analítica",
    "url": "/pngs/Analytics/OpenSearch-Service.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "QuickSight",
    "name": "QuickSight",
    "title": "QuickSight",
    "category": "Analítica",
    "collection": "Analítica",
    "url": "/pngs/Analytics/QuickSight.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Redshift",
    "name": "Redshift",
    "title": "Redshift",
    "category": "Analítica",
    "collection": "Analítica",
    "url": "/pngs/Analytics/Redshift.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "API-Gateway",
    "name": "API Gateway",
    "title": "API Gateway",
    "category": "Integración de Aplicaciones",
    "collection": "Integración de Aplicaciones",
    "url": "/pngs/App-Integration/API-Gateway.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "AppFlow",
    "name": "AppFlow",
    "title": "AppFlow",
    "category": "Integración de Aplicaciones",
    "collection": "Integración de Aplicaciones",
    "url": "/pngs/App-Integration/AppFlow.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "AppSync",
    "name": "AppSync",
    "title": "AppSync",
    "category": "Integración de Aplicaciones",
    "collection": "Integración de Aplicaciones",
    "url": "/pngs/App-Integration/AppSync.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Console-Mobile-Application",
    "name": "Console Mobile Application",
    "title": "Console Mobile Application",
    "category": "Integración de Aplicaciones",
    "collection": "Integración de Aplicaciones",
    "url": "/pngs/App-Integration/Console-Mobile-Application.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "EventBridge",
    "name": "EventBridge",
    "title": "EventBridge",
    "category": "Integración de Aplicaciones",
    "collection": "Integración de Aplicaciones",
    "url": "/pngs/App-Integration/EventBridge.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Express-Workflows",
    "name": "Express Workflows",
    "title": "Express Workflows",
    "category": "Integración de Aplicaciones",
    "collection": "Integración de Aplicaciones",
    "url": "/pngs/App-Integration/Express-Workflows.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Managed-Workflows-for-Apache-Airflow",
    "name": "Managed Workflows for Apache Airflow",
    "title": "Managed Workflows for Apache Airflow",
    "category": "Integración de Aplicaciones",
    "collection": "Integración de Aplicaciones",
    "url": "/pngs/App-Integration/Managed-Workflows-for-Apache-Airflow.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "MQ",
    "name": "MQ",
    "title": "MQ",
    "category": "Integración de Aplicaciones",
    "collection": "Integración de Aplicaciones",
    "url": "/pngs/App-Integration/MQ.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Simple-Notification-Service",
    "name": "Simple Notification Service",
    "title": "Simple Notification Service",
    "category": "Integración de Aplicaciones",
    "collection": "Integración de Aplicaciones",
    "url": "/pngs/App-Integration/Simple-Notification-Service.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Simple-Queue-Service",
    "name": "Simple Queue Service",
    "title": "Simple Queue Service",
    "category": "Integración de Aplicaciones",
    "collection": "Integración de Aplicaciones",
    "url": "/pngs/App-Integration/Simple-Queue-Service.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Step-Functions",
    "name": "Step Functions",
    "title": "Step Functions",
    "category": "Integración de Aplicaciones",
    "collection": "Integración de Aplicaciones",
    "url": "/pngs/App-Integration/Step-Functions.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Managed-Blockchain",
    "name": "Managed Blockchain",
    "title": "Managed Blockchain",
    "category": "Blockchain",
    "collection": "Blockchain",
    "url": "/pngs/Blockchain/Managed-Blockchain.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Quantum-Ledger-Database",
    "name": "Quantum Ledger Database",
    "title": "Quantum Ledger Database",
    "category": "Blockchain",
    "collection": "Blockchain",
    "url": "/pngs/Blockchain/Quantum-Ledger-Database.png?v=1771024599486",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Alexa-For-Business",
    "name": "Alexa For Business",
    "title": "Alexa For Business",
    "category": "Aplicaciones de Negocio",
    "collection": "Aplicaciones de Negocio",
    "url": "/pngs/Business-Applications/Alexa-For-Business.png?v=1771024599487",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Chime-SDK",
    "name": "Chime SDK",
    "title": "Chime SDK",
    "category": "Aplicaciones de Negocio",
    "collection": "Aplicaciones de Negocio",
    "url": "/pngs/Business-Applications/Chime-SDK.png?v=1771024599487",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Chime-Voice-Connector",
    "name": "Chime Voice Connector",
    "title": "Chime Voice Connector",
    "category": "Aplicaciones de Negocio",
    "collection": "Aplicaciones de Negocio",
    "url": "/pngs/Business-Applications/Chime-Voice-Connector.png?v=1771024599487",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Chime",
    "name": "Chime",
    "title": "Chime",
    "category": "Aplicaciones de Negocio",
    "collection": "Aplicaciones de Negocio",
    "url": "/pngs/Business-Applications/Chime.png?v=1771024599487",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Connect",
    "name": "Connect",
    "title": "Connect",
    "category": "Aplicaciones de Negocio",
    "collection": "Aplicaciones de Negocio",
    "url": "/pngs/Business-Applications/Connect.png?v=1771024599487",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Honeycode",
    "name": "Honeycode",
    "title": "Honeycode",
    "category": "Aplicaciones de Negocio",
    "collection": "Aplicaciones de Negocio",
    "url": "/pngs/Business-Applications/Honeycode.png?v=1771024599487",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Pinpoint-APIs",
    "name": "Pinpoint APIs",
    "title": "Pinpoint APIs",
    "category": "Aplicaciones de Negocio",
    "collection": "Aplicaciones de Negocio",
    "url": "/pngs/Business-Applications/Pinpoint-APIs.png?v=1771024599487",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Pinpoint",
    "name": "Pinpoint",
    "title": "Pinpoint",
    "category": "Aplicaciones de Negocio",
    "collection": "Aplicaciones de Negocio",
    "url": "/pngs/Business-Applications/Pinpoint.png?v=1771024599487",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Simple-Email-Service",
    "name": "Simple Email Service",
    "title": "Simple Email Service",
    "category": "Aplicaciones de Negocio",
    "collection": "Aplicaciones de Negocio",
    "url": "/pngs/Business-Applications/Simple-Email-Service.png?v=1771024599487",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Supply-Chain",
    "name": "Supply Chain",
    "title": "Supply Chain",
    "category": "Aplicaciones de Negocio",
    "collection": "Aplicaciones de Negocio",
    "url": "/pngs/Business-Applications/Supply-Chain.png?v=1771024599487",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Wickr",
    "name": "Wickr",
    "title": "Wickr",
    "category": "Aplicaciones de Negocio",
    "collection": "Aplicaciones de Negocio",
    "url": "/pngs/Business-Applications/Wickr.png?v=1771024599487",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "WorkDocs-SDK",
    "name": "WorkDocs SDK",
    "title": "WorkDocs SDK",
    "category": "Aplicaciones de Negocio",
    "collection": "Aplicaciones de Negocio",
    "url": "/pngs/Business-Applications/WorkDocs-SDK.png?v=1771024599487",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "WorkDocs",
    "name": "WorkDocs",
    "title": "WorkDocs",
    "category": "Aplicaciones de Negocio",
    "collection": "Aplicaciones de Negocio",
    "url": "/pngs/Business-Applications/WorkDocs.png?v=1771024599487",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "WorkMail",
    "name": "WorkMail",
    "title": "WorkMail",
    "category": "Aplicaciones de Negocio",
    "collection": "Aplicaciones de Negocio",
    "url": "/pngs/Business-Applications/WorkMail.png?v=1771024599487",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Application-Cost-Profiler",
    "name": "Application Cost Profiler",
    "title": "Application Cost Profiler",
    "category": "Gestión Financiera",
    "collection": "Gestión Financiera",
    "url": "/pngs/Cloud-Financial-Management/Application-Cost-Profiler.png?v=1771024599487",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Billing-Conductor",
    "name": "Billing Conductor",
    "title": "Billing Conductor",
    "category": "Gestión Financiera",
    "collection": "Gestión Financiera",
    "url": "/pngs/Cloud-Financial-Management/Billing-Conductor.png?v=1771024599487",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Budgets",
    "name": "Budgets",
    "title": "Budgets",
    "category": "Gestión Financiera",
    "collection": "Gestión Financiera",
    "url": "/pngs/Cloud-Financial-Management/Budgets.png?v=1771024599487",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Cost-and-Usage-Report",
    "name": "Cost and Usage Report",
    "title": "Cost and Usage Report",
    "category": "Gestión Financiera",
    "collection": "Gestión Financiera",
    "url": "/pngs/Cloud-Financial-Management/Cost-and-Usage-Report.png?v=1771024599487",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Cost-Explorer",
    "name": "Cost Explorer",
    "title": "Cost Explorer",
    "category": "Gestión Financiera",
    "collection": "Gestión Financiera",
    "url": "/pngs/Cloud-Financial-Management/Cost-Explorer.png?v=1771024599487",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Reserved-Instance-Reporting",
    "name": "Reserved Instance Reporting",
    "title": "Reserved Instance Reporting",
    "category": "Gestión Financiera",
    "collection": "Gestión Financiera",
    "url": "/pngs/Cloud-Financial-Management/Reserved-Instance-Reporting.png?v=1771024599487",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Savings-Plans",
    "name": "Savings Plans",
    "title": "Savings Plans",
    "category": "Gestión Financiera",
    "collection": "Gestión Financiera",
    "url": "/pngs/Cloud-Financial-Management/Savings-Plans.png?v=1771024599487",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "App-Runner",
    "name": "App Runner",
    "title": "App Runner",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/App-Runner.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Application-Auto-Scaling",
    "name": "Application Auto Scaling",
    "title": "Application Auto Scaling",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/Application-Auto-Scaling.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Batch",
    "name": "Batch",
    "title": "Batch",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/Batch.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Bottlerocket",
    "name": "Bottlerocket",
    "title": "Bottlerocket",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/Bottlerocket.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Compute-Optimizer",
    "name": "Compute Optimizer",
    "title": "Compute Optimizer",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/Compute-Optimizer.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "EC2-Auto-Scaling",
    "name": "EC2 Auto Scaling",
    "title": "EC2 Auto Scaling",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/EC2-Auto-Scaling.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "EC2-Image-Builder",
    "name": "EC2 Image Builder",
    "title": "EC2 Image Builder",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/EC2-Image-Builder.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "EC2",
    "name": "EC2",
    "title": "EC2",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/EC2.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Elastic-Beanstalk",
    "name": "Elastic Beanstalk",
    "title": "Elastic Beanstalk",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/Elastic-Beanstalk.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Elastic-Fabric-Adapter",
    "name": "Elastic Fabric Adapter",
    "title": "Elastic Fabric Adapter",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/Elastic-Fabric-Adapter.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Fargate",
    "name": "Fargate",
    "title": "Fargate",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/Fargate.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Genomics-CLI",
    "name": "Genomics CLI",
    "title": "Genomics CLI",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/Genomics-CLI.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Lambda",
    "name": "Lambda",
    "title": "Lambda",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/Lambda.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Lightsail",
    "name": "Lightsail",
    "title": "Lightsail",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/Lightsail.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Local-Zones",
    "name": "Local Zones",
    "title": "Local Zones",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/Local-Zones.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "NICE-DCV",
    "name": "NICE DCV",
    "title": "NICE DCV",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/NICE-DCV.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "NICE-EnginFrame",
    "name": "NICE EnginFrame",
    "title": "NICE EnginFrame",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/NICE-EnginFrame.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Nitro-Enclaves",
    "name": "Nitro Enclaves",
    "title": "Nitro Enclaves",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/Nitro-Enclaves.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Outposts-family",
    "name": "Outposts family",
    "title": "Outposts family",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/Outposts-family.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Outposts-rack",
    "name": "Outposts rack",
    "title": "Outposts rack",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/Outposts-rack.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Outposts-servers",
    "name": "Outposts servers",
    "title": "Outposts servers",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/Outposts-servers.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "ParallelCluster",
    "name": "ParallelCluster",
    "title": "ParallelCluster",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/ParallelCluster.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Serverless-Application-Repository",
    "name": "Serverless Application Repository",
    "title": "Serverless Application Repository",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/Serverless-Application-Repository.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "SimSpace-Weaver",
    "name": "SimSpace Weaver",
    "title": "SimSpace Weaver",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/SimSpace-Weaver.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Thinkbox-Deadline",
    "name": "Thinkbox Deadline",
    "title": "Thinkbox Deadline",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/Thinkbox-Deadline.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Thinkbox-Frost",
    "name": "Thinkbox Frost",
    "title": "Thinkbox Frost",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/Thinkbox-Frost.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Thinkbox-Krakatoa",
    "name": "Thinkbox Krakatoa",
    "title": "Thinkbox Krakatoa",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/Thinkbox-Krakatoa.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Thinkbox-Sequoia",
    "name": "Thinkbox Sequoia",
    "title": "Thinkbox Sequoia",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/Thinkbox-Sequoia.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Thinkbox-Stoke",
    "name": "Thinkbox Stoke",
    "title": "Thinkbox Stoke",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/Thinkbox-Stoke.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Thinkbox-XMesh",
    "name": "Thinkbox XMesh",
    "title": "Thinkbox XMesh",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/Thinkbox-XMesh.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "VMware-Cloud-on-AWS",
    "name": "VMware Cloud on AWS",
    "title": "VMware Cloud on AWS",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/VMware-Cloud-on-AWS.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Wavelength",
    "name": "Wavelength",
    "title": "Wavelength",
    "category": "Cómputo",
    "collection": "Cómputo",
    "url": "/pngs/Compute/Wavelength.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "ECS-Anywhere",
    "name": "ECS Anywhere",
    "title": "ECS Anywhere",
    "category": "Contenedores",
    "collection": "Contenedores",
    "url": "/pngs/Containers/ECS-Anywhere.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "EKS-Anywhere",
    "name": "EKS Anywhere",
    "title": "EKS Anywhere",
    "category": "Contenedores",
    "collection": "Contenedores",
    "url": "/pngs/Containers/EKS-Anywhere.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "EKS-Cloud",
    "name": "EKS Cloud",
    "title": "EKS Cloud",
    "category": "Contenedores",
    "collection": "Contenedores",
    "url": "/pngs/Containers/EKS-Cloud.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "EKS-Distro",
    "name": "EKS Distro",
    "title": "EKS Distro",
    "category": "Contenedores",
    "collection": "Contenedores",
    "url": "/pngs/Containers/EKS-Distro.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Elastic-Container-Registry",
    "name": "Elastic Container Registry",
    "title": "Elastic Container Registry",
    "category": "Contenedores",
    "collection": "Contenedores",
    "url": "/pngs/Containers/Elastic-Container-Registry.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Elastic-Container-Service",
    "name": "Elastic Container Service",
    "title": "Elastic Container Service",
    "category": "Contenedores",
    "collection": "Contenedores",
    "url": "/pngs/Containers/Elastic-Container-Service.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Elastic-Kubernetes-Service",
    "name": "Elastic Kubernetes Service",
    "title": "Elastic Kubernetes Service",
    "category": "Contenedores",
    "collection": "Contenedores",
    "url": "/pngs/Containers/Elastic-Kubernetes-Service.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  
  {
    "id": "Red-Hat-OpenShift-Service-on-AWS",
    "name": "Red Hat OpenShift Service on AWS",
    "title": "Red Hat OpenShift Service on AWS",
    "category": "Contenedores",
    "collection": "Contenedores",
    "url": "/pngs/Containers/Red-Hat-OpenShift-Service-on-AWS.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Activate",
    "name": "Activate",
    "title": "Activate",
    "category": "Habilitación del Cliente",
    "collection": "Habilitación del Cliente",
    "url": "/pngs/Customer-Enablement/Activate.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "IQ",
    "name": "IQ",
    "title": "IQ",
    "category": "Habilitación del Cliente",
    "collection": "Habilitación del Cliente",
    "url": "/pngs/Customer-Enablement/IQ.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Managed-Services",
    "name": "Managed Services",
    "title": "Managed Services",
    "category": "Habilitación del Cliente",
    "collection": "Habilitación del Cliente",
    "url": "/pngs/Customer-Enablement/Managed-Services.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Professional-Services",
    "name": "Professional Services",
    "title": "Professional Services",
    "category": "Habilitación del Cliente",
    "collection": "Habilitación del Cliente",
    "url": "/pngs/Customer-Enablement/Professional-Services.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "rePost",
    "name": "rePost",
    "title": "rePost",
    "category": "Habilitación del Cliente",
    "collection": "Habilitación del Cliente",
    "url": "/pngs/Customer-Enablement/rePost.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Support",
    "name": "Support",
    "title": "Support",
    "category": "Habilitación del Cliente",
    "collection": "Habilitación del Cliente",
    "url": "/pngs/Customer-Enablement/Support.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Training-Certification",
    "name": "Training Certification",
    "title": "Training Certification",
    "category": "Habilitación del Cliente",
    "collection": "Habilitación del Cliente",
    "url": "/pngs/Customer-Enablement/Training-Certification.png?v=1771024599489",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Aurora",
    "name": "Aurora",
    "title": "Aurora",
    "category": "Base de Datos",
    "collection": "Base de Datos",
    "url": "/pngs/Database/Aurora.png?v=1771024599490",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Database-Migration-Service",
    "name": "Database Migration Service",
    "title": "Database Migration Service",
    "category": "Base de Datos",
    "collection": "Base de Datos",
    "url": "/pngs/Database/Database-Migration-Service.png?v=1771024599490",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "DocumentDB",
    "name": "DocumentDB",
    "title": "DocumentDB",
    "category": "Base de Datos",
    "collection": "Base de Datos",
    "url": "/pngs/Database/DocumentDB.png?v=1771024599490",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "DynamoDB",
    "name": "DynamoDB",
    "title": "DynamoDB",
    "category": "Base de Datos",
    "collection": "Base de Datos",
    "url": "/pngs/Database/DynamoDB.png?v=1771024599490",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "ElastiCache",
    "name": "ElastiCache",
    "title": "ElastiCache",
    "category": "Base de Datos",
    "collection": "Base de Datos",
    "url": "/pngs/Database/ElastiCache.png?v=1771024599490",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Keyspaces",
    "name": "Keyspaces",
    "title": "Keyspaces",
    "category": "Base de Datos",
    "collection": "Base de Datos",
    "url": "/pngs/Database/Keyspaces.png?v=1771024599490",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "MemoryDB-for-Redis",
    "name": "MemoryDB for Redis",
    "title": "MemoryDB for Redis",
    "category": "Base de Datos",
    "collection": "Base de Datos",
    "url": "/pngs/Database/MemoryDB-for-Redis.png?v=1771024599490",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Neptune",
    "name": "Neptune",
    "title": "Neptune",
    "category": "Base de Datos",
    "collection": "Base de Datos",
    "url": "/pngs/Database/Neptune.png?v=1771024599490",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "RDS-on-VMware",
    "name": "RDS on VMware",
    "title": "RDS on VMware",
    "category": "Base de Datos",
    "collection": "Base de Datos",
    "url": "/pngs/Database/RDS-on-VMware.png?v=1771024599490",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "RDS",
    "name": "RDS",
    "title": "RDS",
    "category": "Base de Datos",
    "collection": "Base de Datos",
    "url": "/pngs/Database/RDS.png?v=1771024599490",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Timestream",
    "name": "Timestream",
    "title": "Timestream",
    "category": "Base de Datos",
    "collection": "Base de Datos",
    "url": "/pngs/Database/Timestream.png?v=1771024599490",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Application-Composer",
    "name": "Application Composer",
    "title": "Application Composer",
    "category": "Herramientas de Desarrollador",
    "collection": "Herramientas de Desarrollador",
    "url": "/pngs/Developer-Tools/Application-Composer.png?v=1771024599490",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Cloud-Control-API",
    "name": "Cloud Control API",
    "title": "Cloud Control API",
    "category": "Herramientas de Desarrollador",
    "collection": "Herramientas de Desarrollador",
    "url": "/pngs/Developer-Tools/Cloud-Control-API.png?v=1771024599490",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Cloud-Development-Kit",
    "name": "Cloud Development Kit",
    "title": "Cloud Development Kit",
    "category": "Herramientas de Desarrollador",
    "collection": "Herramientas de Desarrollador",
    "url": "/pngs/Developer-Tools/Cloud-Development-Kit.png?v=1771024599490",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Cloud9",
    "name": "Cloud9",
    "title": "Cloud9",
    "category": "Herramientas de Desarrollador",
    "collection": "Herramientas de Desarrollador",
    "url": "/pngs/Developer-Tools/Cloud9.png?v=1771024599490",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "CloudShell",
    "name": "CloudShell",
    "title": "CloudShell",
    "category": "Herramientas de Desarrollador",
    "collection": "Herramientas de Desarrollador",
    "url": "/pngs/Developer-Tools/CloudShell.png?v=1771024599490",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "CodeArtifact",
    "name": "CodeArtifact",
    "title": "CodeArtifact",
    "category": "Herramientas de Desarrollador",
    "collection": "Herramientas de Desarrollador",
    "url": "/pngs/Developer-Tools/CodeArtifact.png?v=1771024599490",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "CodeBuild",
    "name": "CodeBuild",
    "title": "CodeBuild",
    "category": "Herramientas de Desarrollador",
    "collection": "Herramientas de Desarrollador",
    "url": "/pngs/Developer-Tools/CodeBuild.png?v=1771024599490",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "CodeCatalyst",
    "name": "CodeCatalyst",
    "title": "CodeCatalyst",
    "category": "Herramientas de Desarrollador",
    "collection": "Herramientas de Desarrollador",
    "url": "/pngs/Developer-Tools/CodeCatalyst.png?v=1771024599490",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "CodeCommit",
    "name": "CodeCommit",
    "title": "CodeCommit",
    "category": "Herramientas de Desarrollador",
    "collection": "Herramientas de Desarrollador",
    "url": "/pngs/Developer-Tools/CodeCommit.png?v=1771024599490",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "CodeDeploy",
    "name": "CodeDeploy",
    "title": "CodeDeploy",
    "category": "Herramientas de Desarrollador",
    "collection": "Herramientas de Desarrollador",
    "url": "/pngs/Developer-Tools/CodeDeploy.png?v=1771024599490",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "CodePipeline",
    "name": "CodePipeline",
    "title": "CodePipeline",
    "category": "Herramientas de Desarrollador",
    "collection": "Herramientas de Desarrollador",
    "url": "/pngs/Developer-Tools/CodePipeline.png?v=1771024599490",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "CodeStar",
    "name": "CodeStar",
    "title": "CodeStar",
    "category": "Herramientas de Desarrollador",
    "collection": "Herramientas de Desarrollador",
    "url": "/pngs/Developer-Tools/CodeStar.png?v=1771024599490",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Command-Line-Interface",
    "name": "Command Line Interface",
    "title": "Command Line Interface",
    "category": "Herramientas de Desarrollador",
    "collection": "Herramientas de Desarrollador",
    "url": "/pngs/Developer-Tools/Command-Line-Interface.png?v=1771024599490",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Corretto",
    "name": "Corretto",
    "title": "Corretto",
    "category": "Herramientas de Desarrollador",
    "collection": "Herramientas de Desarrollador",
    "url": "/pngs/Developer-Tools/Corretto.png?v=1771024599490",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Tools-and-SDKs",
    "name": "Tools and SDKs",
    "title": "Tools and SDKs",
    "category": "Herramientas de Desarrollador",
    "collection": "Herramientas de Desarrollador",
    "url": "/pngs/Developer-Tools/Tools-and-SDKs.png?v=1771024599491",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "X-Ray",
    "name": "X Ray",
    "title": "X Ray",
    "category": "Herramientas de Desarrollador",
    "collection": "Herramientas de Desarrollador",
    "url": "/pngs/Developer-Tools/X-Ray.png?v=1771024599491",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "AppStream",
    "name": "AppStream",
    "title": "AppStream",
    "category": "Computación de Usuario Final",
    "collection": "Computación de Usuario Final",
    "url": "/pngs/End-User-Computing/AppStream.png?v=1771024599491",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "WorkLink",
    "name": "WorkLink",
    "title": "WorkLink",
    "category": "Computación de Usuario Final",
    "collection": "Computación de Usuario Final",
    "url": "/pngs/End-User-Computing/WorkLink.png?v=1771024599491",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "WorkSpaces-Family",
    "name": "WorkSpaces Family",
    "title": "WorkSpaces Family",
    "category": "Computación de Usuario Final",
    "collection": "Computación de Usuario Final",
    "url": "/pngs/End-User-Computing/WorkSpaces-Family.png?v=1771024599491",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Amplify",
    "name": "Amplify",
    "title": "Amplify",
    "category": "Front-End y Móvil",
    "collection": "Front-End y Móvil",
    "url": "/pngs/Front-End-Web-Mobile/Amplify.png?v=1771024599491",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Device-Farm",
    "name": "Device Farm",
    "title": "Device Farm",
    "category": "Front-End y Móvil",
    "collection": "Front-End y Móvil",
    "url": "/pngs/Front-End-Web-Mobile/Device-Farm.png?v=1771024599491",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Location-Service",
    "name": "Location Service",
    "title": "Location Service",
    "category": "Front-End y Móvil",
    "collection": "Front-End y Móvil",
    "url": "/pngs/Front-End-Web-Mobile/Location-Service.png?v=1771024599491",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "GameKit",
    "name": "GameKit",
    "title": "GameKit",
    "category": "Juegos",
    "collection": "Juegos",
    "url": "/pngs/Games/GameKit.png?v=1771024599491",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "GameLift",
    "name": "GameLift",
    "title": "GameLift",
    "category": "Juegos",
    "collection": "Juegos",
    "url": "/pngs/Games/GameLift.png?v=1771024599491",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "GameSparks",
    "name": "GameSparks",
    "title": "GameSparks",
    "category": "Juegos",
    "collection": "Juegos",
    "url": "/pngs/Games/GameSparks.png?v=1771024599491",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Lumberyard",
    "name": "Lumberyard",
    "title": "Lumberyard",
    "category": "Juegos",
    "collection": "Juegos",
    "url": "/pngs/Games/Lumberyard.png?v=1771024599491",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Open-3D-Engine",
    "name": "Open 3D Engine",
    "title": "Open 3D Engine",
    "category": "Juegos",
    "collection": "Juegos",
    "url": "/pngs/Games/Open-3D-Engine.png?v=1771024599491",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Marketplace_Dark",
    "name": "Marketplace Dark",
    "title": "Marketplace Dark",
    "category": "General",
    "collection": "General",
    "url": "/pngs/General-Icons/Marketplace_Dark.png?v=1771024599491",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Marketplace_Light",
    "name": "Marketplace Light",
    "title": "Marketplace Light",
    "category": "General",
    "collection": "General",
    "url": "/pngs/General-Icons/Marketplace_Light.png?v=1771024599491",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "FreeRTOS",
    "name": "FreeRTOS",
    "title": "FreeRTOS",
    "category": "Internet de las Cosas (IoT)",
    "collection": "Internet de las Cosas (IoT)",
    "url": "/pngs/Internet-of-Things/FreeRTOS.png?v=1771024599492",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "IoT-1-Click",
    "name": "IoT 1 Click",
    "title": "IoT 1 Click",
    "category": "Internet de las Cosas (IoT)",
    "collection": "Internet de las Cosas (IoT)",
    "url": "/pngs/Internet-of-Things/IoT-1-Click.png?v=1771024599492",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "IoT-Analytics",
    "name": "IoT Analytics",
    "title": "IoT Analytics",
    "category": "Internet de las Cosas (IoT)",
    "collection": "Internet de las Cosas (IoT)",
    "url": "/pngs/Internet-of-Things/IoT-Analytics.png?v=1771024599492",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "IoT-Button",
    "name": "IoT Button",
    "title": "IoT Button",
    "category": "Internet de las Cosas (IoT)",
    "collection": "Internet de las Cosas (IoT)",
    "url": "/pngs/Internet-of-Things/IoT-Button.png?v=1771024599492",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "IoT-Core",
    "name": "IoT Core",
    "title": "IoT Core",
    "category": "Internet de las Cosas (IoT)",
    "collection": "Internet de las Cosas (IoT)",
    "url": "/pngs/Internet-of-Things/IoT-Core.png?v=1771024599492",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "IoT-Device-Defender",
    "name": "IoT Device Defender",
    "title": "IoT Device Defender",
    "category": "Internet de las Cosas (IoT)",
    "collection": "Internet de las Cosas (IoT)",
    "url": "/pngs/Internet-of-Things/IoT-Device-Defender.png?v=1771024599492",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "IoT-Device-Management",
    "name": "IoT Device Management",
    "title": "IoT Device Management",
    "category": "Internet de las Cosas (IoT)",
    "collection": "Internet de las Cosas (IoT)",
    "url": "/pngs/Internet-of-Things/IoT-Device-Management.png?v=1771024599492",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "IoT-EduKit",
    "name": "IoT EduKit",
    "title": "IoT EduKit",
    "category": "Internet de las Cosas (IoT)",
    "collection": "Internet de las Cosas (IoT)",
    "url": "/pngs/Internet-of-Things/IoT-EduKit.png?v=1771024599492",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "IoT-Events",
    "name": "IoT Events",
    "title": "IoT Events",
    "category": "Internet de las Cosas (IoT)",
    "collection": "Internet de las Cosas (IoT)",
    "url": "/pngs/Internet-of-Things/IoT-Events.png?v=1771024599492",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "IoT-ExpressLink",
    "name": "IoT ExpressLink",
    "title": "IoT ExpressLink",
    "category": "Internet de las Cosas (IoT)",
    "collection": "Internet de las Cosas (IoT)",
    "url": "/pngs/Internet-of-Things/IoT-ExpressLink.png?v=1771024599492",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "IoT-FleetWise",
    "name": "IoT FleetWise",
    "title": "IoT FleetWise",
    "category": "Internet de las Cosas (IoT)",
    "collection": "Internet de las Cosas (IoT)",
    "url": "/pngs/Internet-of-Things/IoT-FleetWise.png?v=1771024599492",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "IoT-Greengrass",
    "name": "IoT Greengrass",
    "title": "IoT Greengrass",
    "category": "Internet de las Cosas (IoT)",
    "collection": "Internet de las Cosas (IoT)",
    "url": "/pngs/Internet-of-Things/IoT-Greengrass.png?v=1771024599492",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "IoT-RoboRunner",
    "name": "IoT RoboRunner",
    "title": "IoT RoboRunner",
    "category": "Internet de las Cosas (IoT)",
    "collection": "Internet de las Cosas (IoT)",
    "url": "/pngs/Internet-of-Things/IoT-RoboRunner.png?v=1771024599492",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "IoT-SiteWise",
    "name": "IoT SiteWise",
    "title": "IoT SiteWise",
    "category": "Internet de las Cosas (IoT)",
    "collection": "Internet de las Cosas (IoT)",
    "url": "/pngs/Internet-of-Things/IoT-SiteWise.png?v=1771024599492",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "IoT-Things-Graph",
    "name": "IoT Things Graph",
    "title": "IoT Things Graph",
    "category": "Internet de las Cosas (IoT)",
    "collection": "Internet de las Cosas (IoT)",
    "url": "/pngs/Internet-of-Things/IoT-Things-Graph.png?v=1771024599492",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "IoT-TwinMaker",
    "name": "IoT TwinMaker",
    "title": "IoT TwinMaker",
    "category": "Internet de las Cosas (IoT)",
    "collection": "Internet de las Cosas (IoT)",
    "url": "/pngs/Internet-of-Things/IoT-TwinMaker.png?v=1771024599492",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Apache-MXNet-on-AWS",
    "name": "Apache MXNet on AWS",
    "title": "Apache MXNet on AWS",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/Apache-MXNet-on-AWS.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Augmented-AI-A2I",
    "name": "Augmented AI A2I",
    "title": "Augmented AI A2I",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/Augmented-AI-A2I.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "CodeGuru",
    "name": "CodeGuru",
    "title": "CodeGuru",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/CodeGuru.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "CodeWhisperer",
    "name": "CodeWhisperer",
    "title": "CodeWhisperer",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/CodeWhisperer.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Comprehend-Medical",
    "name": "Comprehend Medical",
    "title": "Comprehend Medical",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/Comprehend-Medical.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Comprehend",
    "name": "Comprehend",
    "title": "Comprehend",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/Comprehend.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Deep-Learning-AMIs",
    "name": "Deep Learning AMIs",
    "title": "Deep Learning AMIs",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/Deep-Learning-AMIs.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Deep-Learning-Containers",
    "name": "Deep Learning Containers",
    "title": "Deep Learning Containers",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/Deep-Learning-Containers.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "DeepComposer",
    "name": "DeepComposer",
    "title": "DeepComposer",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/DeepComposer.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "DeepLens",
    "name": "DeepLens",
    "title": "DeepLens",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/DeepLens.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "DeepRacer",
    "name": "DeepRacer",
    "title": "DeepRacer",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/DeepRacer.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "DevOps-Guru",
    "name": "DevOps Guru",
    "title": "DevOps Guru",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/DevOps-Guru.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Elastic-Inference",
    "name": "Elastic Inference",
    "title": "Elastic Inference",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/Elastic-Inference.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Forecast",
    "name": "Forecast",
    "title": "Forecast",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/Forecast.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Fraud-Detector",
    "name": "Fraud Detector",
    "title": "Fraud Detector",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/Fraud-Detector.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "HealthLake",
    "name": "HealthLake",
    "title": "HealthLake",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/HealthLake.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Kendra",
    "name": "Kendra",
    "title": "Kendra",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/Kendra.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Lex",
    "name": "Lex",
    "title": "Lex",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/Lex.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Lookout-for-Equipment",
    "name": "Lookout for Equipment",
    "title": "Lookout for Equipment",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/Lookout-for-Equipment.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Lookout-for-Metrics",
    "name": "Lookout for Metrics",
    "title": "Lookout for Metrics",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/Lookout-for-Metrics.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Lookout-for-Vision",
    "name": "Lookout for Vision",
    "title": "Lookout for Vision",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/Lookout-for-Vision.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Monitron",
    "name": "Monitron",
    "title": "Monitron",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/Monitron.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Neuron",
    "name": "Neuron",
    "title": "Neuron",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/Neuron.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Omics",
    "name": "Omics",
    "title": "Omics",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/Omics.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Panorama",
    "name": "Panorama",
    "title": "Panorama",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/Panorama.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Personalize",
    "name": "Personalize",
    "title": "Personalize",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/Personalize.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Polly",
    "name": "Polly",
    "title": "Polly",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/Polly.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Rekognition",
    "name": "Rekognition",
    "title": "Rekognition",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/Rekognition.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "SageMaker-Ground-Truth",
    "name": "SageMaker Ground Truth",
    "title": "SageMaker Ground Truth",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/SageMaker-Ground-Truth.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "SageMaker-Studio-Lab",
    "name": "SageMaker Studio Lab",
    "title": "SageMaker Studio Lab",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/SageMaker-Studio-Lab.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "SageMaker",
    "name": "SageMaker",
    "title": "SageMaker",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/SageMaker.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "TensorFlow-on-AWS",
    "name": "TensorFlow on AWS",
    "title": "TensorFlow on AWS",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/TensorFlow-on-AWS.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Textract",
    "name": "Textract",
    "title": "Textract",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/Textract.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "TorchServe",
    "name": "TorchServe",
    "title": "TorchServe",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/TorchServe.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Transcribe",
    "name": "Transcribe",
    "title": "Transcribe",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/Transcribe.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Translate",
    "name": "Translate",
    "title": "Translate",
    "category": "Machine Learning",
    "collection": "Machine Learning",
    "url": "/pngs/Machine-Learning/Translate.png?v=1771024599493",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "AppConfig",
    "name": "AppConfig",
    "title": "AppConfig",
    "category": "Gestión y Gobierno",
    "collection": "Gestión y Gobierno",
    "url": "/pngs/Management-Governance/AppConfig.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  
  {
    "id": "Auto-Scaling",
    "name": "Auto Scaling",
    "title": "Auto Scaling",
    "category": "Gestión y Gobierno",
    "collection": "Gestión y Gobierno",
    "url": "/pngs/Management-Governance/Auto-Scaling.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Backint-Agent",
    "name": "Backint Agent",
    "title": "Backint Agent",
    "category": "Gestión y Gobierno",
    "collection": "Gestión y Gobierno",
    "url": "/pngs/Management-Governance/Backint-Agent.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Chatbot",
    "name": "Chatbot",
    "title": "Chatbot",
    "category": "Gestión y Gobierno",
    "collection": "Gestión y Gobierno",
    "url": "/pngs/Management-Governance/Chatbot.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "CloudFormation",
    "name": "CloudFormation",
    "title": "CloudFormation",
    "category": "Gestión y Gobierno",
    "collection": "Gestión y Gobierno",
    "url": "/pngs/Management-Governance/CloudFormation.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "CloudTrail",
    "name": "CloudTrail",
    "title": "CloudTrail",
    "category": "Gestión y Gobierno",
    "collection": "Gestión y Gobierno",
    "url": "/pngs/Management-Governance/CloudTrail.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "CloudWatch",
    "name": "CloudWatch",
    "title": "CloudWatch",
    "category": "Gestión y Gobierno",
    "collection": "Gestión y Gobierno",
    "url": "/pngs/Management-Governance/CloudWatch.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Config",
    "name": "Config",
    "title": "Config",
    "category": "Gestión y Gobierno",
    "collection": "Gestión y Gobierno",
    "url": "/pngs/Management-Governance/Config.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Control-Tower",
    "name": "Control Tower",
    "title": "Control Tower",
    "category": "Gestión y Gobierno",
    "collection": "Gestión y Gobierno",
    "url": "/pngs/Management-Governance/Control-Tower.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Distro-for-OpenTelemetry",
    "name": "Distro for OpenTelemetry",
    "title": "Distro for OpenTelemetry",
    "category": "Gestión y Gobierno",
    "collection": "Gestión y Gobierno",
    "url": "/pngs/Management-Governance/Distro-for-OpenTelemetry.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Fault-Injection-Simulator",
    "name": "Fault Injection Simulator",
    "title": "Fault Injection Simulator",
    "category": "Gestión y Gobierno",
    "collection": "Gestión y Gobierno",
    "url": "/pngs/Management-Governance/Fault-Injection-Simulator.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Launch-Wizard",
    "name": "Launch Wizard",
    "title": "Launch Wizard",
    "category": "Gestión y Gobierno",
    "collection": "Gestión y Gobierno",
    "url": "/pngs/Management-Governance/Launch-Wizard.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "License-Manager",
    "name": "License Manager",
    "title": "License Manager",
    "category": "Gestión y Gobierno",
    "collection": "Gestión y Gobierno",
    "url": "/pngs/Management-Governance/License-Manager.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Managed-Grafana",
    "name": "Managed Grafana",
    "title": "Managed Grafana",
    "category": "Gestión y Gobierno",
    "collection": "Gestión y Gobierno",
    "url": "/pngs/Management-Governance/Managed-Grafana.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Managed-Service-for-Prometheus",
    "name": "Managed Service for Prometheus",
    "title": "Managed Service for Prometheus",
    "category": "Gestión y Gobierno",
    "collection": "Gestión y Gobierno",
    "url": "/pngs/Management-Governance/Managed-Service-for-Prometheus.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Management-Console",
    "name": "Management Console",
    "title": "Management Console",
    "category": "Gestión y Gobierno",
    "collection": "Gestión y Gobierno",
    "url": "/pngs/Management-Governance/Management-Console.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "OpsWorks",
    "name": "OpsWorks",
    "title": "OpsWorks",
    "category": "Gestión y Gobierno",
    "collection": "Gestión y Gobierno",
    "url": "/pngs/Management-Governance/OpsWorks.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Organizations",
    "name": "Organizations",
    "title": "Organizations",
    "category": "Gestión y Gobierno",
    "collection": "Gestión y Gobierno",
    "url": "/pngs/Management-Governance/Organizations.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Personal-Health-Dashboard",
    "name": "Personal Health Dashboard",
    "title": "Personal Health Dashboard",
    "category": "Gestión y Gobierno",
    "collection": "Gestión y Gobierno",
    "url": "/pngs/Management-Governance/Personal-Health-Dashboard.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Proton",
    "name": "Proton",
    "title": "Proton",
    "category": "Gestión y Gobierno",
    "collection": "Gestión y Gobierno",
    "url": "/pngs/Management-Governance/Proton.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Resilience-Hub",
    "name": "Resilience Hub",
    "title": "Resilience Hub",
    "category": "Gestión y Gobierno",
    "collection": "Gestión y Gobierno",
    "url": "/pngs/Management-Governance/Resilience-Hub.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Resource-Explorer",
    "name": "Resource Explorer",
    "title": "Resource Explorer",
    "category": "Gestión y Gobierno",
    "collection": "Gestión y Gobierno",
    "url": "/pngs/Management-Governance/Resource-Explorer.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Service-Catalog",
    "name": "Service Catalog",
    "title": "Service Catalog",
    "category": "Gestión y Gobierno",
    "collection": "Gestión y Gobierno",
    "url": "/pngs/Management-Governance/Service-Catalog.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Service-Management-Connector",
    "name": "Service Management Connector",
    "title": "Service Management Connector",
    "category": "Gestión y Gobierno",
    "collection": "Gestión y Gobierno",
    "url": "/pngs/Management-Governance/Service-Management-Connector.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Systems-Manager",
    "name": "Systems Manager",
    "title": "Systems Manager",
    "category": "Gestión y Gobierno",
    "collection": "Gestión y Gobierno",
    "url": "/pngs/Management-Governance/Systems-Manager.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Trusted-Advisor",
    "name": "Trusted Advisor",
    "title": "Trusted Advisor",
    "category": "Gestión y Gobierno",
    "collection": "Gestión y Gobierno",
    "url": "/pngs/Management-Governance/Trusted-Advisor.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Well-Architected-Tool",
    "name": "Well Architected Tool",
    "title": "Well Architected Tool",
    "category": "Gestión y Gobierno",
    "collection": "Gestión y Gobierno",
    "url": "/pngs/Management-Governance/Well-Architected-Tool.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Elastic-Transcoder",
    "name": "Elastic Transcoder",
    "title": "Elastic Transcoder",
    "category": "Servicios Multimedia",
    "collection": "Servicios Multimedia",
    "url": "/pngs/Media-Services/Elastic-Transcoder.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Elemental-Appliances-&-Software",
    "name": "Elemental Appliances & Software",
    "title": "Elemental Appliances & Software",
    "category": "Servicios Multimedia",
    "collection": "Servicios Multimedia",
    "url": "/pngs/Media-Services/Elemental-Appliances-&-Software.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Elemental-Conductor",
    "name": "Elemental Conductor",
    "title": "Elemental Conductor",
    "category": "Servicios Multimedia",
    "collection": "Servicios Multimedia",
    "url": "/pngs/Media-Services/Elemental-Conductor.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Elemental-Delta",
    "name": "Elemental Delta",
    "title": "Elemental Delta",
    "category": "Servicios Multimedia",
    "collection": "Servicios Multimedia",
    "url": "/pngs/Media-Services/Elemental-Delta.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Elemental-Link",
    "name": "Elemental Link",
    "title": "Elemental Link",
    "category": "Servicios Multimedia",
    "collection": "Servicios Multimedia",
    "url": "/pngs/Media-Services/Elemental-Link.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Elemental-Live",
    "name": "Elemental Live",
    "title": "Elemental Live",
    "category": "Servicios Multimedia",
    "collection": "Servicios Multimedia",
    "url": "/pngs/Media-Services/Elemental-Live.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Elemental-MediaConnect",
    "name": "Elemental MediaConnect",
    "title": "Elemental MediaConnect",
    "category": "Servicios Multimedia",
    "collection": "Servicios Multimedia",
    "url": "/pngs/Media-Services/Elemental-MediaConnect.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Elemental-MediaConvert",
    "name": "Elemental MediaConvert",
    "title": "Elemental MediaConvert",
    "category": "Servicios Multimedia",
    "collection": "Servicios Multimedia",
    "url": "/pngs/Media-Services/Elemental-MediaConvert.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Elemental-MediaLive",
    "name": "Elemental MediaLive",
    "title": "Elemental MediaLive",
    "category": "Servicios Multimedia",
    "collection": "Servicios Multimedia",
    "url": "/pngs/Media-Services/Elemental-MediaLive.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Elemental-MediaPackage",
    "name": "Elemental MediaPackage",
    "title": "Elemental MediaPackage",
    "category": "Servicios Multimedia",
    "collection": "Servicios Multimedia",
    "url": "/pngs/Media-Services/Elemental-MediaPackage.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Elemental-MediaStore",
    "name": "Elemental MediaStore",
    "title": "Elemental MediaStore",
    "category": "Servicios Multimedia",
    "collection": "Servicios Multimedia",
    "url": "/pngs/Media-Services/Elemental-MediaStore.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Elemental-MediaTailor",
    "name": "Elemental MediaTailor",
    "title": "Elemental MediaTailor",
    "category": "Servicios Multimedia",
    "collection": "Servicios Multimedia",
    "url": "/pngs/Media-Services/Elemental-MediaTailor.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Elemental-Server",
    "name": "Elemental Server",
    "title": "Elemental Server",
    "category": "Servicios Multimedia",
    "collection": "Servicios Multimedia",
    "url": "/pngs/Media-Services/Elemental-Server.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Interactive-Video-Service",
    "name": "Interactive Video Service",
    "title": "Interactive Video Service",
    "category": "Servicios Multimedia",
    "collection": "Servicios Multimedia",
    "url": "/pngs/Media-Services/Interactive-Video-Service.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  
  {
    "id": "Nimble-Studio",
    "name": "Nimble Studio",
    "title": "Nimble Studio",
    "category": "Servicios Multimedia",
    "collection": "Servicios Multimedia",
    "url": "/pngs/Media-Services/Nimble-Studio.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Application-Discovery-Service",
    "name": "Application Discovery Service",
    "title": "Application Discovery Service",
    "category": "Migración y Transferencia",
    "collection": "Migración y Transferencia",
    "url": "/pngs/Migration-Transfer/Application-Discovery-Service.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Application-Migration-Service",
    "name": "Application Migration Service",
    "title": "Application Migration Service",
    "category": "Migración y Transferencia",
    "collection": "Migración y Transferencia",
    "url": "/pngs/Migration-Transfer/Application-Migration-Service.png?v=1771024599494",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "DataSync",
    "name": "DataSync",
    "title": "DataSync",
    "category": "Migración y Transferencia",
    "collection": "Migración y Transferencia",
    "url": "/pngs/Migration-Transfer/DataSync.png?v=1771024599495",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Mainframe-Modernization",
    "name": "Mainframe Modernization",
    "title": "Mainframe Modernization",
    "category": "Migración y Transferencia",
    "collection": "Migración y Transferencia",
    "url": "/pngs/Migration-Transfer/Mainframe-Modernization.png?v=1771024599495",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Migration-Evaluator",
    "name": "Migration Evaluator",
    "title": "Migration Evaluator",
    "category": "Migración y Transferencia",
    "collection": "Migración y Transferencia",
    "url": "/pngs/Migration-Transfer/Migration-Evaluator.png?v=1771024599495",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Migration-Hub",
    "name": "Migration Hub",
    "title": "Migration Hub",
    "category": "Migración y Transferencia",
    "collection": "Migración y Transferencia",
    "url": "/pngs/Migration-Transfer/Migration-Hub.png?v=1771024599495",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Server-Migration-Service",
    "name": "Server Migration Service",
    "title": "Server Migration Service",
    "category": "Migración y Transferencia",
    "collection": "Migración y Transferencia",
    "url": "/pngs/Migration-Transfer/Server-Migration-Service.png?v=1771024599495",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Transfer-Family",
    "name": "Transfer Family",
    "title": "Transfer Family",
    "category": "Migración y Transferencia",
    "collection": "Migración y Transferencia",
    "url": "/pngs/Migration-Transfer/Transfer-Family.png?v=1771024599495",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "App-Mesh",
    "name": "App Mesh",
    "title": "App Mesh",
    "category": "Redes y Entrega de Contenido",
    "collection": "Redes y Entrega de Contenido",
    "url": "/pngs/Networking-Content-Delivery/App-Mesh.png?v=1771024599495",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Client-VPN",
    "name": "Client VPN",
    "title": "Client VPN",
    "category": "Redes y Entrega de Contenido",
    "collection": "Redes y Entrega de Contenido",
    "url": "/pngs/Networking-Content-Delivery/Client-VPN.png?v=1771024599495",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Cloud-Directory",
    "name": "Cloud Directory",
    "title": "Cloud Directory",
    "category": "Redes y Entrega de Contenido",
    "collection": "Redes y Entrega de Contenido",
    "url": "/pngs/Networking-Content-Delivery/Cloud-Directory.png?v=1771024599495",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Cloud-Map",
    "name": "Cloud Map",
    "title": "Cloud Map",
    "category": "Redes y Entrega de Contenido",
    "collection": "Redes y Entrega de Contenido",
    "url": "/pngs/Networking-Content-Delivery/Cloud-Map.png?v=1771024599495",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Cloud-WAN",
    "name": "Cloud WAN",
    "title": "Cloud WAN",
    "category": "Redes y Entrega de Contenido",
    "collection": "Redes y Entrega de Contenido",
    "url": "/pngs/Networking-Content-Delivery/Cloud-WAN.png?v=1771024599495",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "CloudFront",
    "name": "CloudFront",
    "title": "CloudFront",
    "category": "Redes y Entrega de Contenido",
    "collection": "Redes y Entrega de Contenido",
    "url": "/pngs/Networking-Content-Delivery/CloudFront.png?v=1771024599495",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Direct-Connect",
    "name": "Direct Connect",
    "title": "Direct Connect",
    "category": "Redes y Entrega de Contenido",
    "collection": "Redes y Entrega de Contenido",
    "url": "/pngs/Networking-Content-Delivery/Direct-Connect.png?v=1771024599495",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Elastic-Load-Balancing",
    "name": "Elastic Load Balancing",
    "title": "Elastic Load Balancing",
    "category": "Redes y Entrega de Contenido",
    "collection": "Redes y Entrega de Contenido",
    "url": "/pngs/Networking-Content-Delivery/Elastic-Load-Balancing.png?v=1771024599495",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Global-Accelerator",
    "name": "Global Accelerator",
    "title": "Global Accelerator",
    "category": "Redes y Entrega de Contenido",
    "collection": "Redes y Entrega de Contenido",
    "url": "/pngs/Networking-Content-Delivery/Global-Accelerator.png?v=1771024599495",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Private-5G",
    "name": "Private 5G",
    "title": "Private 5G",
    "category": "Redes y Entrega de Contenido",
    "collection": "Redes y Entrega de Contenido",
    "url": "/pngs/Networking-Content-Delivery/Private-5G.png?v=1771024599495",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "PrivateLink",
    "name": "PrivateLink",
    "title": "PrivateLink",
    "category": "Redes y Entrega de Contenido",
    "collection": "Redes y Entrega de Contenido",
    "url": "/pngs/Networking-Content-Delivery/PrivateLink.png?v=1771024599495",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Route-53",
    "name": "Route 53",
    "title": "Route 53",
    "category": "Redes y Entrega de Contenido",
    "collection": "Redes y Entrega de Contenido",
    "url": "/pngs/Networking-Content-Delivery/Route-53.png?v=1771024599495",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Site-to-Site-VPN",
    "name": "Site to Site VPN",
    "title": "Site to Site VPN",
    "category": "Redes y Entrega de Contenido",
    "collection": "Redes y Entrega de Contenido",
    "url": "/pngs/Networking-Content-Delivery/Site-to-Site-VPN.png?v=1771024599495",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Transit-Gateway",
    "name": "Transit Gateway",
    "title": "Transit Gateway",
    "category": "Redes y Entrega de Contenido",
    "collection": "Redes y Entrega de Contenido",
    "url": "/pngs/Networking-Content-Delivery/Transit-Gateway.png?v=1771024599495",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Verified-Access",
    "name": "Verified Access",
    "title": "Verified Access",
    "category": "Redes y Entrega de Contenido",
    "collection": "Redes y Entrega de Contenido",
    "url": "/pngs/Networking-Content-Delivery/Verified-Access.png?v=1771024599495",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Virtual-Private-Cloud",
    "name": "Virtual Private Cloud",
    "title": "Virtual Private Cloud",
    "category": "Redes y Entrega de Contenido",
    "collection": "Redes y Entrega de Contenido",
    "url": "/pngs/Networking-Content-Delivery/Virtual-Private-Cloud.png?v=1771024599495",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "VPC-Lattice",
    "name": "VPC Lattice",
    "title": "VPC Lattice",
    "category": "Redes y Entrega de Contenido",
    "collection": "Redes y Entrega de Contenido",
    "url": "/pngs/Networking-Content-Delivery/VPC-Lattice.png?v=1771024599495",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Braket",
    "name": "Braket",
    "title": "Braket",
    "category": "Tecnologías Cuánticas",
    "collection": "Tecnologías Cuánticas",
    "url": "/pngs/Quantum-Technologies/Braket.png?v=1771024599495",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "RoboMaker",
    "name": "RoboMaker",
    "title": "RoboMaker",
    "category": "Robótica",
    "collection": "Robótica",
    "url": "/pngs/Robotics/RoboMaker.png?v=1771024599495",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Ground-Station",
    "name": "Ground Station",
    "title": "Ground Station",
    "category": "Satélite",
    "collection": "Satélite",
    "url": "/pngs/Satellite/Ground-Station.png?v=1771024599495",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Artifact",
    "name": "Artifact",
    "title": "Artifact",
    "category": "Seguridad e Identidad",
    "collection": "Seguridad e Identidad",
    "url": "/pngs/Security-Identity-Compliance/Artifact.png?v=1771024599496",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Audit-Manager",
    "name": "Audit Manager",
    "title": "Audit Manager",
    "category": "Seguridad e Identidad",
    "collection": "Seguridad e Identidad",
    "url": "/pngs/Security-Identity-Compliance/Audit-Manager.png?v=1771024599496",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Certificate-Manager",
    "name": "Certificate Manager",
    "title": "Certificate Manager",
    "category": "Seguridad e Identidad",
    "collection": "Seguridad e Identidad",
    "url": "/pngs/Security-Identity-Compliance/Certificate-Manager.png?v=1771024599496",
    "isIsometric": true,
    "scale": 1
  },
  
  {
    "id": "CloudHSM",
    "name": "CloudHSM",
    "title": "CloudHSM",
    "category": "Seguridad e Identidad",
    "collection": "Seguridad e Identidad",
    "url": "/pngs/Security-Identity-Compliance/CloudHSM.png?v=1771024599496",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Cognito",
    "name": "Cognito",
    "title": "Cognito",
    "category": "Seguridad e Identidad",
    "collection": "Seguridad e Identidad",
    "url": "/pngs/Security-Identity-Compliance/Cognito.png?v=1771024599496",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Detective",
    "name": "Detective",
    "title": "Detective",
    "category": "Seguridad e Identidad",
    "collection": "Seguridad e Identidad",
    "url": "/pngs/Security-Identity-Compliance/Detective.png?v=1771024599496",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Directory-Service",
    "name": "Directory Service",
    "title": "Directory Service",
    "category": "Seguridad e Identidad",
    "collection": "Seguridad e Identidad",
    "url": "/pngs/Security-Identity-Compliance/Directory-Service.png?v=1771024599496",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Firewall-Manager",
    "name": "Firewall Manager",
    "title": "Firewall Manager",
    "category": "Seguridad e Identidad",
    "collection": "Seguridad e Identidad",
    "url": "/pngs/Security-Identity-Compliance/Firewall-Manager.png?v=1771024599496",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "GuardDuty",
    "name": "GuardDuty",
    "title": "GuardDuty",
    "category": "Seguridad e Identidad",
    "collection": "Seguridad e Identidad",
    "url": "/pngs/Security-Identity-Compliance/GuardDuty.png?v=1771024599496",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "IAM-Identity-Center",
    "name": "IAM Identity Center",
    "title": "IAM Identity Center",
    "category": "Seguridad e Identidad",
    "collection": "Seguridad e Identidad",
    "url": "/pngs/Security-Identity-Compliance/IAM-Identity-Center.png?v=1771024599496",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Identity-and-Access-Management",
    "name": "Identity and Access Management",
    "title": "Identity and Access Management",
    "category": "Seguridad e Identidad",
    "collection": "Seguridad e Identidad",
    "url": "/pngs/Security-Identity-Compliance/Identity-and-Access-Management.png?v=1771024599496",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Inspector",
    "name": "Inspector",
    "title": "Inspector",
    "category": "Seguridad e Identidad",
    "collection": "Seguridad e Identidad",
    "url": "/pngs/Security-Identity-Compliance/Inspector.png?v=1771024599496",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Key-Management-Service",
    "name": "Key Management Service",
    "title": "Key Management Service",
    "category": "Seguridad e Identidad",
    "collection": "Seguridad e Identidad",
    "url": "/pngs/Security-Identity-Compliance/Key-Management-Service.png?v=1771024599496",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Macie",
    "name": "Macie",
    "title": "Macie",
    "category": "Seguridad e Identidad",
    "collection": "Seguridad e Identidad",
    "url": "/pngs/Security-Identity-Compliance/Macie.png?v=1771024599496",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Network-Firewall",
    "name": "Network Firewall",
    "title": "Network Firewall",
    "category": "Seguridad e Identidad",
    "collection": "Seguridad e Identidad",
    "url": "/pngs/Security-Identity-Compliance/Network-Firewall.png?v=1771024599496",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Private-Certificate-Authority",
    "name": "Private Certificate Authority",
    "title": "Private Certificate Authority",
    "category": "Seguridad e Identidad",
    "collection": "Seguridad e Identidad",
    "url": "/pngs/Security-Identity-Compliance/Private-Certificate-Authority.png?v=1771024599496",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Resource-Access-Manager",
    "name": "Resource Access Manager",
    "title": "Resource Access Manager",
    "category": "Seguridad e Identidad",
    "collection": "Seguridad e Identidad",
    "url": "/pngs/Security-Identity-Compliance/Resource-Access-Manager.png?v=1771024599496",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Secrets-Manager",
    "name": "Secrets Manager",
    "title": "Secrets Manager",
    "category": "Seguridad e Identidad",
    "collection": "Seguridad e Identidad",
    "url": "/pngs/Security-Identity-Compliance/Secrets-Manager.png?v=1771024599496",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Security-Hub",
    "name": "Security Hub",
    "title": "Security Hub",
    "category": "Seguridad e Identidad",
    "collection": "Seguridad e Identidad",
    "url": "/pngs/Security-Identity-Compliance/Security-Hub.png?v=1771024599496",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Security-Lake",
    "name": "Security Lake",
    "title": "Security Lake",
    "category": "Seguridad e Identidad",
    "collection": "Seguridad e Identidad",
    "url": "/pngs/Security-Identity-Compliance/Security-Lake.png?v=1771024599496",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Shield",
    "name": "Shield",
    "title": "Shield",
    "category": "Seguridad e Identidad",
    "collection": "Seguridad e Identidad",
    "url": "/pngs/Security-Identity-Compliance/Shield.png?v=1771024599496",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Signer",
    "name": "Signer",
    "title": "Signer",
    "category": "Seguridad e Identidad",
    "collection": "Seguridad e Identidad",
    "url": "/pngs/Security-Identity-Compliance/Signer.png?v=1771024599496",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Verified-Permissions",
    "name": "Verified Permissions",
    "title": "Verified Permissions",
    "category": "Seguridad e Identidad",
    "collection": "Seguridad e Identidad",
    "url": "/pngs/Security-Identity-Compliance/Verified-Permissions.png?v=1771024599496",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "WAF",
    "name": "WAF",
    "title": "WAF",
    "category": "Seguridad e Identidad",
    "collection": "Seguridad e Identidad",
    "url": "/pngs/Security-Identity-Compliance/WAF.png?v=1771024599496",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Backup",
    "name": "Backup",
    "title": "Backup",
    "category": "Almacenamiento",
    "collection": "Almacenamiento",
    "url": "/pngs/Storage/Backup.png?v=1771024599497",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "EFS",
    "name": "EFS",
    "title": "EFS",
    "category": "Almacenamiento",
    "collection": "Almacenamiento",
    "url": "/pngs/Storage/EFS.png?v=1771024599497",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Elastic-Block-Store",
    "name": "Elastic Block Store",
    "title": "Elastic Block Store",
    "category": "Almacenamiento",
    "collection": "Almacenamiento",
    "url": "/pngs/Storage/Elastic-Block-Store.png?v=1771024599497",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Elastic-Disaster-Recovery",
    "name": "Elastic Disaster Recovery",
    "title": "Elastic Disaster Recovery",
    "category": "Almacenamiento",
    "collection": "Almacenamiento",
    "url": "/pngs/Storage/Elastic-Disaster-Recovery.png?v=1771024599497",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "File-Cache",
    "name": "File Cache",
    "title": "File Cache",
    "category": "Almacenamiento",
    "collection": "Almacenamiento",
    "url": "/pngs/Storage/File-Cache.png?v=1771024599497",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "FSx-for-Lustre",
    "name": "FSx for Lustre",
    "title": "FSx for Lustre",
    "category": "Almacenamiento",
    "collection": "Almacenamiento",
    "url": "/pngs/Storage/FSx-for-Lustre.png?v=1771024599497",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "FSx-for-NetApp-ONTAP",
    "name": "FSx for NetApp ONTAP",
    "title": "FSx for NetApp ONTAP",
    "category": "Almacenamiento",
    "collection": "Almacenamiento",
    "url": "/pngs/Storage/FSx-for-NetApp-ONTAP.png?v=1771024599497",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "FSx-for-OpenZFS",
    "name": "FSx for OpenZFS",
    "title": "FSx for OpenZFS",
    "category": "Almacenamiento",
    "collection": "Almacenamiento",
    "url": "/pngs/Storage/FSx-for-OpenZFS.png?v=1771024599497",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "FSx-for-WFS",
    "name": "FSx for WFS",
    "title": "FSx for WFS",
    "category": "Almacenamiento",
    "collection": "Almacenamiento",
    "url": "/pngs/Storage/FSx-for-WFS.png?v=1771024599497",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "FSx",
    "name": "FSx",
    "title": "FSx",
    "category": "Almacenamiento",
    "collection": "Almacenamiento",
    "url": "/pngs/Storage/FSx.png?v=1771024599497",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "S3-on-Outposts",
    "name": "S3 on Outposts",
    "title": "S3 on Outposts",
    "category": "Almacenamiento",
    "collection": "Almacenamiento",
    "url": "/pngs/Storage/S3-on-Outposts.png?v=1771024599497",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Simple-Storage-Service-Glacier",
    "name": "Simple Storage Service Glacier",
    "title": "Simple Storage Service Glacier",
    "category": "Almacenamiento",
    "collection": "Almacenamiento",
    "url": "/pngs/Storage/Simple-Storage-Service-Glacier.png?v=1771024599497",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Simple-Storage-Service",
    "name": "Simple Storage Service",
    "title": "Simple Storage Service",
    "category": "Almacenamiento",
    "collection": "Almacenamiento",
    "url": "/pngs/Storage/Simple-Storage-Service.png?v=1771024599497",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Snowball-Edge",
    "name": "Snowball Edge",
    "title": "Snowball Edge",
    "category": "Almacenamiento",
    "collection": "Almacenamiento",
    "url": "/pngs/Storage/Snowball-Edge.png?v=1771024599497",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Snowball",
    "name": "Snowball",
    "title": "Snowball",
    "category": "Almacenamiento",
    "collection": "Almacenamiento",
    "url": "/pngs/Storage/Snowball.png?v=1771024599497",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Snowcone",
    "name": "Snowcone",
    "title": "Snowcone",
    "category": "Almacenamiento",
    "collection": "Almacenamiento",
    "url": "/pngs/Storage/Snowcone.png?v=1771024599497",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Snowmobile",
    "name": "Snowmobile",
    "title": "Snowmobile",
    "category": "Almacenamiento",
    "collection": "Almacenamiento",
    "url": "/pngs/Storage/Snowmobile.png?v=1771024599497",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Storage-Gateway",
    "name": "Storage Gateway",
    "title": "Storage Gateway",
    "category": "Almacenamiento",
    "collection": "Almacenamiento",
    "url": "/pngs/Storage/Storage-Gateway.png?v=1771024599497",
    "isIsometric": true,
    "scale": 1
  },
  {
    "id": "Sumerian",
    "name": "Sumerian",
    "title": "Sumerian",
    "category": "VR / AR",
    "collection": "VR / AR",
    "url": "/pngs/VR-AR/Sumerian.png?v=1771024599497",
    "isIsometric": true,
    "scale": 1
  }
]
};

export default generatedAwsIcons;
